-- v2 (Supplier-ID): penambahan nilai enum. Dipisah dari 0005 karena nilai enum baru tidak bisa dipakai di transaksi yang sama.
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'COURIER';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PROCESSING';          -- diterima mitra: produksi/picking/QC
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'READY_FOR_PICKUP';    -- dikemas & berlabel, menunggu kurir
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'DELIVERY_FAILED';     -- gagal antar, menunggu kirim ulang / batal
ALTER TYPE shipment_status ADD VALUE IF NOT EXISTS 'DELIVERY_FAILED';
ALTER TYPE shipment_status ADD VALUE IF NOT EXISTS 'RETURNED';
ALTER TYPE evidence_owner ADD VALUE IF NOT EXISTS 'QC';
ALTER TYPE evidence_owner ADD VALUE IF NOT EXISTS 'PACKAGE';
ALTER TYPE evidence_owner ADD VALUE IF NOT EXISTS 'DELIVERY';
ALTER TYPE evidence_owner ADD VALUE IF NOT EXISTS 'TICKET';
ALTER TYPE evidence_kind ADD VALUE IF NOT EXISTS 'QC_PHOTO';
ALTER TYPE evidence_kind ADD VALUE IF NOT EXISTS 'PACKING_PHOTO';
ALTER TYPE evidence_kind ADD VALUE IF NOT EXISTS 'DELIVERY_PROOF';
ALTER TYPE evidence_kind ADD VALUE IF NOT EXISTS 'HANDOVER_PHOTO';
ALTER TYPE evidence_kind ADD VALUE IF NOT EXISTS 'TICKET_ATTACHMENT';
ALTER TYPE ledger_account ADD VALUE IF NOT EXISTS 'RESELLER_MARGIN_REVENUE';
ALTER TYPE ledger_component ADD VALUE IF NOT EXISTS 'RESELLER_MARGIN';
ALTER TYPE ledger_component ADD VALUE IF NOT EXISTS 'PAYOUT_REVERSAL';
ALTER TYPE payout_status ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE payout_status ADD VALUE IF NOT EXISTS 'REVERSED';
ALTER TYPE payout_status ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'EXPIRED';
